name: Ransomwatch with Playwright

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      torproxy:
        image: ghcr.io/joshhighet/torsocc:latest
        ports:
          - 9050:9050

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements-playwright.txt
          playwright install

      - name: Run Playwright Scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python3 Valse.py  # Valse.py 내부에서 playwright_scraper 사용한다고 가정